site_name: Pokepy
theme:
    name: 'material'

nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Usage: 'usage.md'
    - Contributing: 'contributing.md'
    - Authors: 'authors.md'
    - History: 'history.md'

extra_css:
  - 'stylesheets/extra.css'
