# Config file for automatic testing at circleci.com

version: 2

jobs:
  py27:
    docker:
      - image: circleci/python:2.7.16
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest discover tests

  py33:
    docker:
      - image: circleci/python:3.3.6
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest

  py34:
    docker:
      - image: circleci/python:3.4.10
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest

  py35:
    docker:
      - image: circleci/python:3.5.7
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest

  py36:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest

  py37:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: sudo pip install -r requirements.txt -r requirements-dev.txt
      - run:
          name: Lint
          command: python -m pylint pokepy tests setup.py
      - run:
          name: Run Tests
          command: python -m unittest
      - run:
          name: Run Coverage tool
          command: coverage run --source pokepy -m unittest
      - run:
          name: Generate XML coverage report
          command: coverage xml
      - run:
          name: Upload Coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  py38:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest

workflows:
  version: 2
  run_tests:
    jobs:
      - py27
      - py33
      - py34
      - py35
      - py36
      - py37
      - py38
